# Analysis of Experiment 10
The purpose of this notebook is to analyze the trained models from Experiment 10.

## Imports

In [1]:
import json
import os
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm

import jax.numpy as jnp

## Analysis

In [2]:
job_folder = "../../../results/experiment_10"
search_results = []

for task_id in range(384):
    metrics_loc = os.path.join(job_folder, f"task_{task_id}/metrics_history.csv")
    test_loss_min = pd.read_csv(metrics_loc)['test_loss'].min()
    test_acc_max = pd.read_csv(metrics_loc)['test_accuracy'].max()
    
    var_explained_loc = os.path.join(job_folder, f"task_{task_id}/cumulative_variance.npy")
    var_exp_arr = jnp.load(var_explained_loc)
    
    params_loc = os.path.join(job_folder, f"task_{task_id}/params.json")
    with open(params_loc, 'r') as f:
        json_params = json.load(f)
    
    seed = json_params.get('seed', 0)
    alpha = json_params.get('alpha', 0.1)
    
    task_stats_params = {
        'test_loss_min': test_loss_min,
        'test_acc_max': test_acc_max,
        'cum_var': var_exp_arr[2].item(),
        'seed': seed,
        'alpha': alpha,
    }
    search_results.append(task_stats_params)

In [6]:
df_search_results = pd.DataFrame(search_results)
df_search_results[df_search_results['alpha'] == 0.4].sort_values('cum_var', ascending=False).head(25)

     test_loss_min  test_acc_max   cum_var  seed  alpha
0         0.000018           1.0  0.903970     0    0.4
60        0.000011           1.0  0.899292    60    0.4
59        0.000020           1.0  0.897366    59    0.4
76        0.000029           1.0  0.896576    76    0.4
29        0.000018           1.0  0.891527    29    0.4
106       0.000024           1.0  0.891101   106    0.4
36        0.000066           1.0  0.890610    36    0.4
117       0.000015           1.0  0.890537   117    0.4
125       0.000010           1.0  0.885582   125    0.4
44        0.000012           1.0  0.884711    44    0.4
15        0.000025           1.0  0.884242    15    0.4
116       0.000018           1.0  0.884054   116    0.4
127       0.000020           1.0  0.882671   127    0.4
85        0.000015           1.0  0.881288    85    0.4
18        0.000018           1.0  0.880609    18    0.4
102       0.000014           1.0  0.880061   102    0.4
86        0.000023           1.0  0.879772    86    0.4
79        0.000015           1.0  0.878199    79    0.4
81        0.000012           1.0  0.876586    81    0.4
56        0.000024           1.0  0.876222    56    0.4
109       0.000019           1.0  0.875533   109    0.4
37        0.000019           1.0  0.875238    37    0.4
58        0.000013           1.0  0.874409    58    0.4
5         0.000014           1.0  0.872123     5    0.4
40        0.000043           1.0  0.869435    40    0.4

In [4]:
df_search_results[df_search_results['alpha'] == 0.2].sort_values('cum_var', ascending=False).head(25)

     test_loss_min  test_acc_max   cum_var  seed  alpha
143       0.000072           1.0  0.860209   143    0.2
216       0.000035           1.0  0.860159   216    0.2
164       0.000029           1.0  0.853548   164    0.2
129       0.000026           1.0  0.848832   129    0.2
231       0.000049           1.0  0.843481   231    0.2
162       0.000060           1.0  0.842749   162    0.2
134       0.000034           1.0  0.842700   134    0.2
235       0.000044           1.0  0.842351   235    0.2
202       0.000048           1.0  0.840320   202    0.2
197       0.000034           1.0  0.840244   197    0.2
232       0.000038           1.0  0.839011   232    0.2
131       0.000033           1.0  0.838553   131    0.2
175       0.000031           1.0  0.837427   175    0.2
191       0.000029           1.0  0.836721   191    0.2
204       0.000031           1.0  0.836711   204    0.2
247       0.000028           1.0  0.836462   247    0.2
230       0.000042           1.0  0.835855   230    0.2
238       0.000040           1.0  0.835539   238    0.2
149       0.000042           1.0  0.833755   149    0.2
240       0.000048           1.0  0.833539   240    0.2
183       0.000033           1.0  0.833407   183    0.2
217       0.000022           1.0  0.833369   217    0.2
244       0.000064           1.0  0.833272   244    0.2
233       0.000042           1.0  0.832369   233    0.2
219       0.000052           1.0  0.831957   219    0.2

In [5]:
df_search_results[df_search_results['alpha'] == float(10/75)].sort_values('cum_var', ascending=False).head(25)

     test_loss_min  test_acc_max   cum_var  seed     alpha
341       0.000075           1.0  0.835188   341  0.133333
345       0.000061           1.0  0.833868   345  0.133333
367       0.000084           1.0  0.833567   367  0.133333
358       0.000069           1.0  0.831745   358  0.133333
371       0.000079           1.0  0.828638   371  0.133333
291       0.000058           1.0  0.827883   291  0.133333
363       0.000078           1.0  0.827238   363  0.133333
265       0.000067           1.0  0.825366   265  0.133333
361       0.000078           1.0  0.822617   361  0.133333
260       0.000072           1.0  0.820639   260  0.133333
279       0.000072           1.0  0.818972   279  0.133333
297       0.000092           1.0  0.818274   297  0.133333
377       0.000073           1.0  0.818256   377  0.133333
366       0.000067           1.0  0.817979   366  0.133333
343       0.000062           1.0  0.817927   343  0.133333
327       0.000087           1.0  0.817415   327  0.133333
313       0.000059           1.0  0.817198   313  0.133333
369       0.000055           1.0  0.817095   369  0.133333
328       0.000109           1.0  0.816639   328  0.133333
360       0.000094           1.0  0.816494   360  0.133333
306       0.000100           1.0  0.816356   306  0.133333
351       0.000074           1.0  0.816343   351  0.133333
261       0.000049           1.0  0.816279   261  0.133333
318       0.000059           1.0  0.816199   318  0.133333
256       0.000060           1.0  0.816140   256  0.133333